grades/urls.py
from django.conf.urls import url
from grades import views

urlpatterns = [
    url(r'^$', views.grading_systems, name="grading_systems_home"),
    url(r'^grading_systems/$', views.grading_systems, name="grading_systems"),
    url(r'^add_grade/$', views.add_grading_system, name="add_grade"),
    url(r'^add_grade/(?P<system_id>\d+)/$', views.add_grading_system,
        name="edit_grade"),
]

online_test/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'online_test.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^exam/', include('yaksh.urls', namespace='yaksh', app_name='yaksh')),
    url(r'^exam/reset/', include('yaksh.urls_password_reset')),
    url(r'^', include('social.apps.django_app.urls', namespace='social')),
    url(r'^grades/', include('grades.urls', namespace='grades', app_name='grades')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yaksh/urls.py
    url(r'^quizzes/$', views.quizlist_user, name='quizlist_user'),
    url(r'^quizzes/(?P<enrolled>\w+)/$', views.quizlist_user, name='quizlist_user'),
    url(r'^results/$', views.results_user),
    url(r'^start/(?P<questionpaper_id>\d+)/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.start),
    url(r'^start/(?P<attempt_num>\d+)/(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.start),
    url(r'^quit/(?P<attempt_num>\d+)/(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.quit),
    url(r'^complete/$', views.complete),
    url(r'^complete/(?P<attempt_num>\d+)/(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',\
            views.complete),
    url(r'^register/$', views.user_register, name="register"),
    url(r'^(?P<q_id>\d+)/check/$', views.check, name="check"),
    url(r'^get_result/(?P<uid>\d+)/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_result),
    url(r'^(?P<q_id>\d+)/check/(?P<attempt_num>\d+)/(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',\
            views.check, name="check"),
    url(r'^(?P<q_id>\d+)/skip/(?P<attempt_num>\d+)/(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip),
    url(r'^(?P<q_id>\d+)/skip/(?P<next_q>\d+)/(?P<attempt_num>\d+)/(?P<module_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.skip),
    url(r'^enroll_request/(?P<course_id>\d+)/$', views.enroll_request, name='enroll_request'),
    url(r'^self_enroll/(?P<course_id>\d+)/$', views.self_enroll, name='self_enroll'),
    url(r'^view_answerpaper/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)$',
        views.view_answerpaper, name='view_answerpaper'),
    url(r'^show_lesson/(?P<lesson_id>\d+)/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.show_lesson, name='show_lesson'),
    url(r'^quizzes/view_module/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.view_module, name='view_module'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<current_unit_id>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^next_unit/(?P<course_id>\d+)/(?P<module_id>\d+)/(?P<current_unit_id>\d+)/(?P<first_unit>\d+)/$',
        views.get_next_unit, name='next_unit'),
    url(r'^course_modules/(?P<course_id>\d+)/$',
        views.course_modules, name='course_modules'),
    url(r'^manage/$', views.prof_manage, name='manage'),
    url(r'^manage/addquestion/$', views.add_question, name="add_question"),
    url(r'^manage/addquestion/(?P<question_id>\d+)/$', views.add_question,
                                        name="add_question"),
    url(r'^manage/addquiz/$', views.add_quiz, name='add_quiz'),
    url(r'^manage/add_exercise/$', views.add_exercise, name='add_exercise'),
    url(r'^manage/add_exercise/(?P<quiz_id>\d+)/$', views.add_exercise,
        name='edit_exercise'),
    url(r'^manage/add_exercise/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.add_exercise, name='edit_exercise'),
    url(r'^manage/addquiz/(?P<quiz_id>\d+)/$',
        views.add_quiz, name='edit_quiz'),
    url(r'^manage/addquiz/(?P<quiz_id>\d+)/(?P<course_id>\d+)$',
        views.add_quiz, name='edit_quiz'),
    url(r'^manage/gradeuser/$', views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
            views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/(?P<course_id>\d+)/$',
            views.grade_user, name="grade_user"),
    url(r'^manage/gradeuser/(?P<quiz_id>\d+)/(?P<user_id>\d+)/(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
            views.grade_user, name="grade_user"),
    url(r'^manage/questions/$', views.show_all_questions, name="show_questions"),
    url(r'^manage/monitor/$', views.monitor, name="monitor"),
    url(r'^manage/monitor/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.monitor, name="monitor"),
    url(r'^manage/user_data/(?P<user_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.user_data, name="user_data"),
    url(r'^manage/user_data/(?P<user_id>\d+)/$', views.user_data),
    url(r'^manage/quiz/designquestionpaper/(?P<quiz_id>\d+)/$', views.design_questionpaper,
        name='design_questionpaper'),
    url(r'^manage/designquestionpaper/(?P<quiz_id>\d+)/(?P<questionpaper_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/designquestionpaper/(?P<quiz_id>\d+)/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.design_questionpaper, name='designquestionpaper'),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/statistics/question/(?P<questionpaper_id>\d+)/(?P<attempt_number>\d+)/(?P<course_id>\d+)/$',
        views.show_statistics, name="show_statistics"),
    url(r'^manage/download_quiz_csv/(?P<course_id>\d+)/(?P<quiz_id>\d+)/$',
        views.download_quiz_csv, name="download_quiz_csv"),
    url(r'^manage/duplicate_course/(?P<course_id>\d+)/$',
        views.duplicate_course, name='duplicate_course'),
    url(r'manage/courses/$', views.courses, name='courses'),
    url(r'manage/add_course/$', views.add_course, name='add_course'),
    url(r'manage/edit_course/(?P<course_id>\d+)$', views.add_course, name='edit_course'),
    url(r'manage/course_detail/(?P<course_id>\d+)/$', views.course_detail, name='course_detail'),
    url(r'manage/enroll/(?P<course_id>\d+)/(?P<user_id>\d+)/$', views.enroll,
            name="enroll_user"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.enroll, {'was_rejected': True}),
    url(r'manage/upload_users/(?P<course_id>\d+)/$', views.upload_users, name="upload_users"),
    url(r'manage/send_mail/(?P<course_id>\d+)/$', views.send_mail, name="send_mail"),
    url(r'manage/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$', views.reject,
            name="reject_user"),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/(?P<user_id>\d+)/$',
        views.reject, {'was_enrolled': True}, name="reject_user"),
    url(r'manage/toggle_status/(?P<course_id>\d+)/$', views.toggle_course_status,
            name="toggle_course_status"),
    url(r'^ajax/questions/filter/$', views.ajax_questions_filter,
                name="questions_filter"),
    url(r'^editprofile/$', views.edit_profile, name='edit_profile'),
    url(r'^viewprofile/$', views.view_profile, name='view_profile'),
    url(r'^manage/enroll/(?P<course_id>\d+)/$', views.enroll, name="enroll_users"),
    url(r'manage/enroll/rejected/(?P<course_id>\d+)/$',
        views.enroll, {'was_rejected': True}),
    url(r'manage/enrolled/reject/(?P<course_id>\d+)/$',
        views.reject, {'was_enrolled': True}, name="reject_users"),
    url(r'^manage/searchteacher/(?P<course_id>\d+)/$', views.search_teacher),
    url(r'^manage/addteacher/(?P<course_id>\d+)/$', views.add_teacher, name='add_teacher'),
    url(r'^manage/remove_teachers/(?P<course_id>\d+)/$', views.remove_teachers, name='remove_teacher'),
    url(r'^manage/download_questions/$', views.show_all_questions,
                        name="show_questions"),
    url(r'^manage/upload_questions/$', views.show_all_questions,
                        name="show_questions"),
    url(r'^manage/grader/$', views.grader, name='grader'),
    url(r'^manage/regrade/question/(?P<course_id>\d+)/(?P<question_id>\d+)/$',
            views.regrade, name='regrade'),
    url(r'^manage/regrade/questionpaper/(?P<course_id>\d+)/(?P<question_id>\d+)/(?P<questionpaper_id>\d+)/$',
            views.regrade, name='regrade'),
    url(r'^manage/regrade/answerpaper/(?P<course_id>\d+)/(?P<question_id>\d+)/(?P<answerpaper_id>\d+)/$',
            views.regrade, name='regrade'),
    url(r'^manage/regrade/paper/(?P<course_id>\d+)/(?P<answerpaper_id>\d+)/$',
            views.regrade, name='regrade'),
    url(r'^manage/check_plagiarism/$',
            views.check_plagiarism, name='check_plagiarism'),
    url(r'^manage/check_plagiarism/(?P<course_id>\d+)/(?P<questionpaper_id>\d+)/$',
            views.check_plagiarism, name='check_plagiarism'),
    url(r'^manage/(?P<mode>godmode|usermode)/(?P<quiz_id>\d+)/(?P<course_id>\d+)/$',
        views.test_quiz),
    url(r'^manage/create_demo_course/$', views.create_demo_course),
    url(r'^manage/courses/download_course_csv/(?P<course_id>\d+)/$',
        views.download_course_csv, name="download_course_csv"),
    url(r'^manage/download/user_assignment/(?P<question_id>\d+)/(?P<user_id>\d+)/(?P<quiz_id>\d+)/$',
        views.download_assignment_file, name="download_user_assignment"),
    url(r'^manage/download/quiz_assignments/(?P<quiz_id>\d+)/$',
        views.download_assignment_file, name="download_quiz_assignment"),
    url(r'^manage/courses/download_yaml_template/',
        views.download_yaml_template, name="download_yaml_template"),
    url(r'^manage/download_sample_csv/',
        views.download_sample_csv, name="download_sample_csv"),
    url(r'^manage/courses/edit_lesson/$',
        views.edit_lesson, name="edit_lesson"),
    url(r'^manage/courses/edit_lesson/(?P<lesson_id>\d+)/$',
        views.edit_lesson, name="edit_lesson"),
    url(r'^manage/courses/edit_lesson/(?P<lesson_id>\d+)/(?P<course_id>\d+)/$',
        views.edit_lesson, name="edit_lesson"),
    url(r'^manage/courses/designmodule/(?P<module_id>\d+)/$',
        views.design_module, name="design_module"),
    url(r'^manage/courses/designmodule/(?P<module_id>\d+)/(?P<course_id>\d+)/$',
        views.design_module, name="design_module"),
    url(r'^manage/courses/all_quizzes/$',
        views.show_all_quizzes, name="show_all_quizzes"),
    url(r'^manage/courses/all_lessons/$',
        views.show_all_lessons, name="show_all_lessons"),
    url(r'^manage/courses/lesson/preview/$',

grades/models.py
from django.db import models
from django.contrib.auth.models import User


class GradingSystem(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(default='About the grading system!')
    creator = models.ForeignKey(User, null=True, blank=True)

    def get_grade(self, marks):
        ranges = self.graderange_set.all()
        lower_limits = ranges.values_list('lower_limit', flat=True)
        upper_limits = ranges.values_list('upper_limit', flat=True)
        lower_limit = self._get_lower_limit(marks, lower_limits)
        upper_limit = self._get_upper_limit(marks, upper_limits)
        grade_range = ranges.filter(lower_limit=lower_limit,
                                    upper_limit=upper_limit).first()
        if grade_range:
            return grade_range.grade

    def _get_upper_limit(self, marks, upper_limits):
        greater_than = [upper_limit for upper_limit in upper_limits
                        if upper_limit > marks]
        if greater_than:
            return min(greater_than, key=lambda x: x-marks)

    def _get_lower_limit(self, marks, lower_limits):
        less_than = []
        for lower_limit in lower_limits:
            if lower_limit == marks:
                return lower_limit
            if lower_limit < marks:
                less_than.append(lower_limit)
        if less_than:
            return max(less_than, key=lambda x: x-marks)

    def __str__(self):
        return self.name.title()


class GradeRange(models.Model):
    system = models.ForeignKey(GradingSystem)
    lower_limit = models.FloatField()
    upper_limit = models.FloatField()
    grade = models.CharField(max_length=10)
    description = models.CharField(max_length=127, null=True, blank=True)

grades/forms.py
from grades.models import GradingSystem
from django import forms


class GradingSystemForm(forms.ModelForm):
    class Meta:
        model = GradingSystem
        fields = ['name', 'description']

grades/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.forms import inlineformset_factory
from grades.forms import GradingSystemForm
from grades.models import GradingSystem, GradeRange


@login_required
def grading_systems(request):
    user = request.user
    default_grading_system = GradingSystem.objects.get(name='default')
    grading_systems = GradingSystem.objects.filter(creator=user)
    return render(request, 'grading_systems.html', {'default_grading_system':
                  default_grading_system, 'grading_systems': grading_systems})


@login_required
def add_grading_system(request, system_id=None):
    user = request.user
    grading_system = None
    if system_id is not None:
        grading_system = GradingSystem.objects.get(id=system_id)
    GradeRangeFormSet = inlineformset_factory(GradingSystem, GradeRange,
                                              fields='__all__', extra=0)
    grade_form = GradingSystemForm(instance=grading_system)
    is_default = grading_system is not None and grading_system.name == 'default'

    if request.method == 'POST':
        formset = GradeRangeFormSet(request.POST, instance=grading_system)
        grade_form = GradingSystemForm(request.POST, instance=grading_system)
        if grade_form.is_valid():
            system = grade_form.save(commit=False)
            system.creator = user
            system.save()
            system_id = system.id
        if formset.is_valid():
            formset.save()
        if 'add' in request.POST:
            GradeRangeFormSet = inlineformset_factory(GradingSystem, GradeRange,
                                                      fields='__all__', extra=1)
    formset = GradeRangeFormSet(instance=grading_system)

    return render(request, 'add_grades.html', {'formset': formset,
                  'grade_form': grade_form, "system_id": system_id,
                  'is_default': is_default})

grades/templates/add_grades.html
{% extends "manage.html" %}
{% block main %}
<html>
<a href="{% url 'grades:grading_systems'%}" class="btn btn-danger"> Back to Grading Systems </a>
<br><br>
<p><b>Note: For grade range lower limit is inclusive and upper limit is exclusive</b></p>
<br>
{% if not system_id  %}
    <form action="{% url 'grades:add_grade' %}" method="POST">
{% else %}
    <form action="{% url 'grades:edit_grade' system_id %}" method="POST">
{% endif %}
    {% csrf_token %}
    <table class="table">
      {{ grade_form }}
    </table>
      {{ formset.management_form }}
      <br>
      <b><u>Grade Ranges</u></b>
      <hr>
      {% for form in formset %}
      <div>
            {{ form }}
      </div>
      <hr>
      {% endfor %}
  {% if not is_default %}
      <input type="submit" id="add" name="add" value="Add" class="btn btn-info">
      <input type="submit" id="save" name="save" value="Save" class="btn btn-success">
  {% else %}
    <p><b>Note: This is a default grading system. You cannot change this.</b></p>
  {% endif %}
</form>
</html>
{% endblock %}

grades/templates/grading_systems.html
{% extends "manage.html" %}
{% block main %}
<html>
    <a href="{% url 'grades:add_grade' %}" class="btn btn-primary"> Add a Grading System </a>
    <a href="{% url 'yaksh:courses' %}" class="btn btn-danger"> Back to Courses </a>
    <br><br>
    <b> Available Grading Systems: </b>
    <table class="table">
        <tr>
            <th>Grading System</th>
            <th>Grading Ranges</th>
        </tr>
        <tr>
            <td>
            <a href="{% url 'grades:edit_grade' default_grading_system.id %}">
            {{ default_grading_system.name }}</a> (<b>Default Grading System</b>)
            </td>
            <td>
                <table class="table">
                    <tr>
                        <th>Lower Limit</th>
                        <th>Upper Limit</th>
                        <th>Grade</th>
                        <th>Description</th>
                    </tr>
                    {% for range in default_grading_system.graderange_set.all %}
                        <tr>
                            <td>{{range.lower_limit}}</td>
                            <td>{{range.upper_limit}}</td>
                            <td>{{range.grade}}</td>
                            {% if range.description %}
                                <td>{{range.description}}</td>
                            {% else %}
                                <td>------</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </td>
        </tr>
        {% if grading_systems %}
        {% for system in grading_systems %}
            <tr>
            <td>
            <a href="{% url 'grades:edit_grade' system.id %}">{{ system.name }}</a>
            </td>
            <td>
                <table class="table">
                    <tr>
                        <th>Lower Limit</th>
                        <th>Upper Limit</th>
                        <th>Grade</th>
                        <th>Description</th>
                    </tr>
                    {% for range in system.graderange_set.all %}
                        <tr>
                            <td>{{range.lower_limit}}</td>
                            <td>{{range.upper_limit}}</td>
                            <td>{{range.grade}}</td>
                            {% if range.description %}
                                <td>{{range.description}}</td>
                            {% else %}
                                <td>------</td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </td>
            </tr>
        {% endfor %}
    </table>
    {% endif %}
</html>
{% endblock %}